// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM5yRf4ddEnTP7V-w5ZJR9TtePWSUwOjs',
    appId: '1:849536775476:web:56904a257565c53de6a161',
    messagingSenderId: '849536775476',
    projectId: 'tomato-companion',
    authDomain: 'tomato-companion.firebaseapp.com',
    storageBucket: 'tomato-companion.firebasestorage.app',
    measurementId: 'G-N9QTZHKYWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ex47PCPf0Opll028ZXODJdgxb7EmjAI',
    appId: '1:849536775476:android:ac4a5981fae7e352e6a161',
    messagingSenderId: '849536775476',
    projectId: 'tomato-companion',
    storageBucket: 'tomato-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTbqoLct4xurVkMHVViNpq_wSbnIn_ZQ',
    appId: '1:849536775476:ios:cb9a0add88c89c1ee6a161',
    messagingSenderId: '849536775476',
    projectId: 'tomato-companion',
    storageBucket: 'tomato-companion.firebasestorage.app',
    iosBundleId: 'com.madina.tomatoCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPTbqoLct4xurVkMHVViNpq_wSbnIn_ZQ',
    appId: '1:849536775476:ios:cb9a0add88c89c1ee6a161',
    messagingSenderId: '849536775476',
    projectId: 'tomato-companion',
    storageBucket: 'tomato-companion.firebasestorage.app',
    iosBundleId: 'com.madina.tomatoCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM5yRf4ddEnTP7V-w5ZJR9TtePWSUwOjs',
    appId: '1:849536775476:web:513458b14aca5fc0e6a161',
    messagingSenderId: '849536775476',
    projectId: 'tomato-companion',
    authDomain: 'tomato-companion.firebaseapp.com',
    storageBucket: 'tomato-companion.firebasestorage.app',
    measurementId: 'G-2M5VT27K56',
  );

}