import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app.dart';
import 'firebase_options.dart';
import 'services/auth_service.dart';

void main() async {
  // Ensures Flutter's widget tree binding is ready before async work in main.
  WidgetsFlutterBinding.ensureInitialized();

  // Connect to the tomato-companion Firebase project using the platform-
  // specific credentials generated by `flutterfire configure`.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Sign the user in anonymously so they have a stable Firebase UID before
  // the UI tries to read from /users/{uid}/... in Firestore. This satisfies
  // our security rules without forcing the user to create an account.
  final auth = AuthService();
  await auth.signInAnonymouslyIfNeeded();

  runApp(const TomatoApp());
}